<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks Condition="'$(UseReleaseAssembly)' != 'true'">net48;net8.0-windows</TargetFrameworks>
    <TargetFrameworks Condition="'$(UseReleaseAssembly)' == 'true'">net48</TargetFrameworks>
    <OutputPath Condition="'$(UseReleaseAssembly)' == 'true'">bin/ReleaseAssembly/$(Configuration)/</OutputPath>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/AcadPaletteSetXData.UI/AcadPaletteSetXData.UI.csproj" Condition="'$(UseReleaseAssembly)' != 'true'" />
    <ProjectReference Include="../../src/acadPaletteSetXDATA/acadPaletteSetXDATA.csproj" Condition="'$(UseReleaseAssembly)' == 'true'" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
